version: '3'

services:
  postgres:
    image: 'postgres:14.4'
    container_name: 'java-postgres-expApi'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=web'
    ports:
      - "5432:5432"
